# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: kidosol3106@gmail.com
author_name: Jack Wang
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
project_short_description: A JupyterLab extension.
python_name: jupyterlab_apod
repository: https://github.com/KaitoPotato/JupyterExtension.git
test: true

